use anyhow::Result;
use std::fs::File;
use std::io::Write;

fn main() -> Result<()> {
    let html_content = r#"
    <!DOCTYPE html>
    <html>
    <head>
        <title>Rust Site</title>
        <style>
            body {
                background-color: #777;
                font-family: sans-serif;
                padding-left: 1rem;
            }
            a {
                color: #6E260E;
            }
        </style>
    </head>
    <body>
        <h1>Rust-Generated Site</h1>
        <p>This site was generated by <a target="_blank" href="nnn">this Rust code</a>.</p>
        <p>See also <a target="_blank" href="https://tanguay-eu.vercel.app/forays/283">my notes</a> on this project.
        <hr/>
    </body>
    </html>
    "#;

    let mut file = File::create("/var/www/rust/index.html")?;
    file.write_all(html_content.as_bytes())?;

    Ok(())

}
